name: amos-radar
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - tqdm
  - seaborn
  - numpy
  - matplotlib
  - pandas
  - xarray
  - arm_pyart
  - netCDF4
  - cartopy
  - h5py
  - seaborn
  - requests
